/**
 * Generates docs/RTP_REPORT.md from a large Monte-Carlo run.
 * Usage: npm run rtp:report  [rounds-per-bucket]   (default 10,000,000)
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { STRATEGIES, runBucket } from '../engine/__tests__/simulate';
import { DEFAULT_CONFIG } from '../engine/config';

const rounds = Number(process.argv[2] ?? 10_000_000);
const targetRtp = 1 - DEFAULT_CONFIG.houseEdge;

const started = Date.now();
const results = STRATEGIES.map((s, i) => {
  process.stdout.write(`  running ${s.name} …\n`);
  return runBucket(s, rounds, 7000 + i);
});
const secs = ((Date.now() - started) / 1000).toFixed(1);

const totalRounds = rounds * STRATEGIES.length;
const rows = results
  .map(
    (r) =>
      `| ${r.name} | ${r.rounds.toLocaleString()} | ${(r.rtp * 100).toFixed(4)}% | ` +
      `${(r.deviation * 100 >= 0 ? '+' : '') + (r.deviation * 100).toFixed(4)}% | ` +
      `${(r.stdError * 100).toFixed(4)}% | ${r.withinTolerance ? '✅' : '❌'} |`,
  )
  .join('\n');

const allPass = results.every((r) => r.withinTolerance);

const md = `# RTP Monte-Carlo Report

_Auto-generated by \`npm run rtp:report\`. Do not edit by hand._

- **Configured RTP:** ${(targetRtp * 100).toFixed(2)}%  (house edge ${(DEFAULT_CONFIG.houseEdge * 100).toFixed(2)}%)
- **Rounds per strategy bucket:** ${rounds.toLocaleString()}
- **Total rounds simulated:** ${totalRounds.toLocaleString()}
- **Wall time:** ${secs}s
- **Verdict:** ${allPass ? '✅ every strategy realises the configured RTP within tolerance' : '❌ a bucket fell outside tolerance'}

Tolerance is \`max(0.1%, 4·SE)\` — the standard-error term keeps the assertion
statistically sound for high-variance buckets (large targets, Beyond wager),
where 0.1% is below the achievable precision even at ten million rounds.

| Strategy bucket | Rounds | Realised RTP | Deviation | Std. error | Pass |
| --- | ---: | ---: | ---: | ---: | :---: |
${rows}

## What this proves

Player choices — disposition, ambition tier, push/coast/tend pacing, re-declare,
when to rest, and the optional Beyond wager — move only **variance**. Every
bucket converges to the same ${(targetRtp * 100).toFixed(2)}% expected return.
This is the crash-family martingale property: because the mortality point \`M\`
is hidden and independent of the player's (also-independent) rest decision,
\`EV = stake · (1 − e)\` for every strategy. See \`docs/MATH.md\` for the proof.
`;

const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'RTP_REPORT.md');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, md);
process.stdout.write(`\nWrote ${outPath}\n${allPass ? 'ALL BUCKETS PASS' : 'SOME BUCKETS FAILED'}\n`);
if (!allPass) process.exit(1);
